### ISSUE TITLE
code availability?

### ISSUE THREAD

**Issue by monperrus** [pietroborrello/raindrop#1]
Hi @pietroborrello 

cc @bbaudry

Just seen your paper on arxiv, it's **really** cool! We would love to experiment with raindrop.

When would you plan to push the code?

Thanks!

**Comment by pietroborrello** [comment]
Hi @monperrus thank you for the appreciation!
We plan to release it during the [DSN21](http://dsn2021.ntu.edu.tw/) conference (late June).

**Comment by monperrus** [comment]
thanks, looking forward to it!

**Comment by monperrus** [comment]
Hi @pietroborrello 

Your paper reminds me of compiling with move instructions only

[mov is Turing-complete](http://faq8.ru/file.php/5/470/movTuringcomplete.pdf)

**Comment by pietroborrello** [comment]
Instructions to request access to the code are provided in the readme!
